<?php

Route::get('/', 'WelcomeController@index');
// Route::get('/home', 'WelcomeController@index');
// Route::get('/home', 'WelcomeController@index')->name('home');
Route::get('/', 'WelcomeController@index')->name('welcome');
Auth::routes();
Route::get('/mylists', 'MyListsController@index')->name('mylists');
Route::post('/singlelist', 'SingleListController@store');
Route::get('/mylists/{id}', 'SingleListController@show');
Route::get('/singlelist/create', 'SingleListController@create');
Route::get('/singlelist/deleteList/{id}', 'SingleListController@deleteList');
Route::get('/singlelist/{id}/edit', 'SingleListController@edit');
Route::get('/singlelist/{id}', 'SingleListController@show')->name('singlelist');
Route::any('createlist', ['as' => 'createlist', function() { return redirect('singlelist/create'); } ]);
Route::get('/singlelist/resetresults/{id}', 'SingleListController@resetResults')->name('resetresults');
Route::get('/singlelist/generatePDF/{id}', 'SingleListController@generatePDF')->name('generatePDF');
Route::get('/singlelist/generateCSV/{id}', 'SingleListController@generateCSV')->name('generateCSV');
Route::group(['middleware' => ['web']], function(){
    Route::resource('singlelist', 'SingleListController');
});
Route::get('/singleword/{id}/editNative', 'SingleWordController@editNative');
Route::get('/singleword/{id}/editForeign', 'SingleWordController@editForeign');
Route::get('/native/create', 'NativeController@create')->name('createNative');
Route::post('/native/create', 'NativeController@store');
Route::get('/foreign/create', 'ForeignController@create')->name('createForeign');
Route::post('/foreign/create', 'ForeignController@store');
Route::get('/singlelist/deleteWord/{id}', 'SingleWordController@deleteWord');
Route::resource('singleword', 'SingleWordController');
Route::get('/learningnative', 'LearningNativeWordsController@index')->name('learningnative');
Route::patch('/learningnative/checkWord', 'LearningNativeWordsController@checkWord')->name('checkNativeWord');
Route::get('/learningforeign', 'LearningForeignWordsController@index')->name('learningforeign');
Route::patch('/learningforeign/checkWord', 'LearningForeignWordsController@checkWord')->name('checkForeignWord');
Route::get('/setRoute', 'LearningNativeWordsController@setRoute')->name('setRoute');
Route::get('/stats', 'StatsController@index')->name('stats');
Route::get('/settings', 'SettingsController@index')->name('settings');
Route::get('/settings/editName', 'SettingsController@editName')->name('editName');
Route::patch('/settings/updateName', 'SettingsController@updateName')->name('updateName');
Route::get('/settings/changeEmail', 'SettingsController@changeEmail')->name('changeEmail');
Route::patch('/settings/updateEmail', 'SettingsController@updateEmail')->name('updateEmail');
Route::get('/settings/changePassword', 'SettingsController@changePassword')->name('changePassword');
Route::patch('/settings/updatePassword', 'SettingsController@updatePassword')->name('updatePassword');
Route::get('/settings/confirmDeleteAccount', 'SettingsController@confirmDeleteAccount')->name('confirmDeleteAccount');
Route::get('/settings/deleteAll', 'SettingsController@deleteAll')->name('deleteAll');
Route::get('/addlist', 'AddListController@index');
Route::get('/singlelist', 'SingleListController@index');
Route::get('/admin', 'AdminController@index')->name('admin');
Route::get('/admin/changeToUser', 'AdminController@changeToUser')->name('changeToUser');
Route::get('/admin/changeToAdmin', 'AdminController@changeToAdmin')->name('changeToAdmin');
Route::get('/admin/changePasswordByAdmin', 'AdminController@changePasswordByAdmin')->name('changePasswordByAdmin');
Route::patch('/admin/updatePasswordByAdmin', 'AdminController@updatePasswordByAdmin')->name('updatePasswordByAdmin');
Route::get('/admin/lockAccount', 'AdminController@lockAccount')->name('lockAccount');
Route::get('/admin/unlockAccount', 'AdminController@unlockAccount')->name('unlockAccount');
Route::get('/admin/deleteAccountByAdmin', 'AdminController@deleteAccountByAdmin')->name('deleteAccountByAdmin');
Route::get('/admin/confirmDeleteAccountByAdmin', 'AdminController@confirmDeleteAccountByAdmin')->name('confirmDeleteAccountByAdmin');
Route::any('{query}', function() { return redirect('/mylists'); })->where('query', '.*');